### ISSUE TITLE
Serverless Django?

### ISSUE THREAD

**Issue by gardner** [aws-samples/serverless-django-cdk-sample#7]
This is a really great example but the name of the repository is a bit confusing. When I read it I expected to find some way of running django code in AWS Lambda. 

It was a bit dissapointing to find that it just uses a serverless RDS instance.

Why does this example use a serverless version of RDS?

**Comment by FreddyFFM** [comment]
Sorry for the title misleading you. Still the sample relies only on serverless AWS services like RDS and Fargate. This example gives a guidance to run Django on AWS leverage scalability and resilience without the need of maintaining the underlying infrastructure - finally fully serverless.
